# Generated by Django 4.2.2 on 2023-06-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='Pid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
